imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app_locales: en|de

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        shop_url_origin: %shop_url_origin%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

ongr_elasticsearch:
    analysis:
        analyzer:
            urlAnalyzer:
                type: custom
                tokenizer: keyword
                filter: [lowercase]
    connections:
        default:
            index_name: ongr2
            analysis:
                analyzer:
                    - urlAnalyzer
            settings:
                number_of_replicas: %elasticsearch_number_of_replicas%
                number_of_shards: %elasticsearch_number_of_shards%
    managers:
        default:
            connection: default
            mappings:
                - AppBundle

ongr_filter_manager:
    managers:
        product_list:
            filters:
                - search
                - pager
                - sorting
                - color
                - brand
                - material
                - app_category
            repository: 'es.manager.default.product'
    filters:
        multi_choice:
            color:
                request_field: 'c'
                field: color
                size: 10
            material:
                request_field: 'm'
                field: material
                size: 10
        choice:
            brand:
                request_field: 'b'
                field: brand
                size: 10
        match:
            search:
                request_field: 'q'
                field: title
        pager:
            pager:
                request_field: 'page'
                count_per_page: 12
                max_pages: 10
        sort:
            sorting:
                request_field: 'sort'
                choices:
                    - { label: filter.price_asc, field: price, default: true }
                    - { label: filter.price_desc, field: price, order: desc }
                    - { label: filter.title_asc, field: title }
                    - { label: filter.title_desc, field: title, order: desc }

ongr_router:
    seo_routes:
        product: AppBundle:Product:show
        category: AppBundle:Product:list
        content: AppBundle:Content:show

ongr_api:
    versions:
        v3:
            endpoints:
                product:
                    repository: es.manager.default.product
                    variants: true
                category:
                    repository: es.manager.default.category
